export default {
  G: "Glycine",
  P: "Proline",
  A: "Alanine",
  V: "Valine",
  L: "Leucine",
  I: "Isoleucine",
  M: "Methionine",
  C: "Cysteine",
  F: "Phenylalanine",
  Y: "Tyrosine",
  W: "Tryptophan",
  H: "Histidine",
  K: "Lysine",
  R: "Arginine",
  Q: "Glutamine",
  N: "Asparagine",
  E: "Glutamic",
  D: "Aspartic",
  S: "Serine",
  T: "Threonine",
};
